# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
  

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

    working_directory: ~/repo

    steps:
      - checkout

      # Revert to traditional pip install when build refactored, in the meantime:
      - run:
          name: lscpu
          command: lscpu
      # Run code lints
      - run:
          name: ls -la
          command: ls -la

workflows:
  version: 2
  run-tests-and-rebase-master:
    jobs:
      - build